source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/powerline.kak"
plug "Delapouite/kakoune-buffers"
plug "alexherbo2/auto-pairs.kak"

# auto-pairs config
map global user s ':<space>auto-pairs-surround<ret>' -docstring 'Surround'

colorscheme zenburn
add-highlighter global/ number-lines -hlcursor
# Highlight 80th column
add-highlighter global/ column 80 default,rgb:303030
addhl global/ wrap

set global ui_options ncurses_assistant=cat

# Indentation settings

set global tabstop 4
set global indentwidth 4

hook -group kakrc global BufSetOption filetype=ruby %{
  set buffer tabstop 2
  set buffer indentwidth 2
}

map global user \' '<a-S>'                                  -docstring 'Alt-S shortcut'
map global user ',' ':write<ret>'                           -docstring ':w shortcut'
map global user 'B' ':info-buffers<ret>'                    -docstring 'show buffers'
map global user 'b' ':enter-user-mode buffers<ret>'         -docstring 'enter buffers user mode'
map global user 'r' "|ruby -e 's=STDIN.read; si=s.to_i; p " -docstring 'pipe selections to ruby oneliner'
map global user 'c' '<a-|>pbcopy<ret>'                      -docstring 'clipboard copy current selection'
map global user 'p' '|pbpaste<ret>'                         -docstring 'clipboard paste current selection'
map global user 'h' 'Gh'                                    -docstring 'extend selection to beginning of line'
map global user 'l' 'Gl'                                    -docstring 'extend selection to end of line'
map global user 'n' ':new<ret>'                             -docstring 'open new tmux split of kak'
map global user 'F' ':set buffer filetype '                 -docstring 'shortcut for manual filetype setting'
map global user 'K' ':e ~/.config/kak/kakrc<ret>'           -docstring 'open kakoune config file'

map global user '=' ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>' -docstring 'replace selections with prompted math results against values'

map global normal '#' ':comment-line<ret>' -docstring 'Comment line'
map global normal 'D' ';Gld'               -docstring 'Delete to end of line'
map global normal '<backspace>' ';<space>' -docstring 'reduce selection to just active cursor'

hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}
