source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/powerline.kak"
plug "Delapouite/kakoune-buffers"
plug "alexherbo2/auto-pairs.kak"

# auto-pairs config
map global user s -docstring 'Surround' ':<space>auto-pairs-surround<ret>'

colorscheme zenburn
add-highlighter global/ number-lines -hlcursor
# Highlight 80th column
add-highlighter global/ column 80 default,rgb:303030
addhl global/ wrap

set global ui_options ncurses_assistant=cat

# Indentation settings

set global tabstop 4
set global indentwidth 4

hook -group kakrc global BufSetOption filetype=ruby %{
  set buffer tabstop 2
  set buffer indentwidth 2
}

map global user -docstring 'Alt-S shortcut' \' '<a-S>'
map global user -docstring 'split on ", "' ',' 'S, <ret>'
map global user -docstring 'show buffers' 'b' ':info-buffers<ret>'
map global user -docstring 'enter buffers user mode' 'B' ':enter-user-mode buffers<ret>'
map global user -docstring 'pipe selections to ruby oneliner' 'r' "|ruby -e 's=STDIN.read; si=s.to_i; p "
map global user -docstring 'clipboard copy current selection' 'c' '<a-|>pbcopy<ret>'
map global user -docstring 'clipboard paste current selection' 'p' '|pbpaste<ret>'
map global user -docstring 'replace selections with prompted math results against values' = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'

map global normal -docstring 'Comment line' '#' :comment-line
map global normal -docstring 'Delete to end of line' 'D' ';Gld'

hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}
