source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/powerline.kak"
plug "Delapouite/kakoune-buffers"

colorscheme zenburn
add-highlighter global/ number-lines
set global ui_options ncurses_assistant=cat

# Indentation settings

set global tabstop 4
set global indentwidth 4

hook -group kakrc global BufSetOption filetype=ruby %{
  set buffer tabstop 2
  set buffer indentwidth 2
}

map global user \' '<a-S>' -docstring 'Alt-S shortcut'

map global normal '#' :comment-line -docstring 'Comment line'
map global normal 'D' ';Gld' -docstring 'Delete to end of line'

map global user ',' 'S, <ret>' -docstring 'split on ", "'
map global user 'b' ':info-buffers<ret>' -docstring 'show buffers'
map global user 'B' ':enter-user-mode buffers<ret>' -docstring 'enter buffers user mode'
map global user 'r' "|ruby -e 's=STDIN.read; si=s.to_i; p " -docstring 'pipe selections to ruby oneliner'
